### ISSUE TITLE
Additional function for the natural log of the fugacity

### ISSUE THREAD

**Issue by DiegoTMelfi** [zmeri/PC-SAFT#100]
Dear,

This is not an actual issue with the codes, but would it be possible to create another function that evaluates the natural log of the fugacity of the component in the phase (essentially identical to pcsaft_fugcoef, but without the last exponential operation)? 
I ask this because I am doing polymer phase equilibria and for polymers, the natural log of the fugacity in a liquid phase is of the order of negative 1000. And when we do exp(-1000) we get zero because double precision cannot compute such a small number, which is what the program is returning.
I could try to do it myself, but my cython background is null, and this might be something that other people can benefit from.

Thank you in advance,
Diego

**Comment by DiegoTMelfi** [comment]
Hi,

Thank you for your response and your directions! After a little struggle, I created the new function, which is working just fine.
Diego

**Comment by zmeri** [comment]
I'm glad to hear that you got it working. Would you be willing to submit a
pull request and contribute your improvements?
