### ISSUE TITLE
regarding pcsaft.flashTQ

### ISSUE THREAD

**Issue by PPG2889** [zmeri/PC-SAFT#111]
Hi, 

Its regarding pcsaft.flashTQ() code.

![Screenshot 2023-10-20 161658](https://github.com/zmeri/PC-SAFT/assets/148561011/002f996e-498c-4431-9398-2ec13a9d4f24)

You've selected a methane-benzene binary system as a test case for the flashTQ() code. Surprisingly, the code executes successfully for only the initial three mole fraction values (0.025, 0.0502, 0.0823) at a temperature of 421.05 K. Unfortunately, for all other mole fraction values, the code encounters issues.

I've also cross-verified the code with experimental data from other sources for a similar system, and the problem persists. It's imperative that we investigate the root cause of this issue. I kindly request your assistance in identifying and resolving the underlying problem within the code.

**Comment by zmeri** [comment]
This was already discussed in issue #98.
