### ISSUE TITLE
Eigen 

### ISSUE THREAD

**Issue by laubapires** [zmeri/PC-SAFT#112]
Cythonize is not working "Cannot open include file: 'externals/eigen/Eigen/Dense': No such file or directory"

Eigen's official git repository has moved to https://gitlab.com/libeigen/eigen
And it is required to update your git clones & submodules to https://gitlab.com/libeigen/eigen.git as soon as possible.

**Comment by mv-per** [comment]
please try cloning using `git clone --recurse-submodules https://github.com/zmeri/PC-SAFT.git`

**Comment by zmeri** [comment]
Eigen's URL is already set to https://gitlab.com/libeigen/eigen in the .gitmodules file. As mv-per mentioned, maybe you just need to use the --recursive option so that git will also pull Eigen. I did a fresh clone of PC-SAFT just to check, and it worked for me and Eigen was downloaded as well.
