### ISSUE TITLE
Thanks, where is the implementaion

### ISSUE THREAD

**Issue by samiit** [zmeri/PC-SAFT#75]
Hi,

Thanks very much for taking on this massive task. I had a question regarding where the functions are implemented in the code. I could not locate them anywhere in this repository. E.g., I was looking where the implementation of `pcsaft_den_cpp` is but could not find. Can you please direct me to know where it is located? Thanks.

Sam

**Comment by zmeri** [comment]
For sure. The code is in the pcsaft_electrolyte.cpp file. For instance, [here](https://github.com/zmeri/PC-SAFT/blob/master/pcsaft_electrolyte.cpp#L2382) is where the pcsaft_den_cpp function is.
