### ISSUE TITLE
Polymer modeling

### ISSUE THREAD

**Issue by kaige-web** [zmeri/PC-SAFT#90]
Hello! Thank you very much for the PC-SAFT installation package. It helped me a lot in calculating thermodynamic properties.

I currently have a modeling problem about polymers.  I find that your code seems to consist mainly of association schemes 2B and 4C.  However, the association scheme for drugs and polymers is often (3,3) (0, 2) or others rather than 4C (2,2) or 2B (1,1). 
https://pubs.acs.org/doi/10.1021/acs.jced.0c00912

May I ask you  whether you have relevant plans to add relevant association schemes.

**Comment by kaige-web** [comment]
Hello！I got a response from professor Sadowski's group about the association issue. The details of the response are as follows:

The association question: This can be expressed more general, calculating the number of unbonded speres for each association type. Maybe the appendix /SI of anke Prudics Paper helps here (https://pubs.acs.org/doi/10.1021/mp400729x) or the (similar) paragraph from Chapman et al. (https://pubs.acs.org/doi/abs/10.1021/ie00104a021) (mixtures of accociating spheres – the model is applicable also to molecules with a higher number of association sites, as for example polymers or the mentioned example indomethacin.

I hope these contents can be helpful to expand the application scope of your software because there may be hundreds of association sites for polymers.

**Comment by zmeri** [comment]
Thanks for the information!
