### ISSUE TITLE
instructions for association schemes

### ISSUE THREAD

**Issue by iurisegtovich** [zmeri/PC-SAFT#96]
Hi, I'm trying to understand the syntax for association schemes,

in the documentation, it says:

>assoc_scheme : list, shape (n,)
    The types of association sites for each component. Use None for molecules without association sites. **If a molecule has multiple association sites, use a nested list for that component to specify the association scheme for each site.** The accepted association schemes are those given by Huang and Radosz (1990): 1, 2A, 2B, 3A, 3B, 4A, 4B, 4C. If e_assoc and vol_a are given but assoc_scheme is not, the 2B association scheme is assumed (which would, for example, correspond to one hydroxyl functional group).

but it was not clear to me how to pass the parameters "e_assoc" and "vol_a" for each site in a mixture where one or two molecules have multiple association sites using different schemes

could you provide an example for that usage, regarding the syntax for the scheme logic and how to pass parameter values in the correct order?

**Comment by zmeri** [comment]
Hi. Currently, the code uses the same _e_assoc_ and _vol_a_ parameters for all the sites on a molecule. It is not currently possible to specify those association parameters for each individual site. I have only ever used multiple sites with molecules for which the associating sites are similar and _e_assoc_ and _vol_a_ could be kept the same.
